name: gsea_browser
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - dash=2.14.2
  - dash-bio=1.0.2
  - pandas=2.1.4
  - numpy=1.26.2
  - plotly=5.18.0
  - gunicorn=21.2.0
  - python-dotenv=1.0.0
  - pip